import { ArrowRight, CheckCircle2 } from "lucide-react";
import { trackConversionEvent } from "@/lib/conversion";
import { WhatsAppLink } from "./WhatsAppLink";

const closingPoints = ["Informar atividade, cidade, faturamento esperado e momento da empresa.", "Entender se o caso é abertura de CNPJ, desenquadramento MEI, troca de contador ou revisão tributária.", "Saber quais documentos e próximos passos fazem sentido antes da proposta."];

export function FinalCTA() {
  return (
    <section id="cta" className="relative overflow-hidden border-t border-white/5 bg-[#0A0D1E] py-10 md:py-24"><div className="relative z-10 mx-auto max-w-[1280px] px-5 sm:px-6"><div className="grid items-start gap-9 md:gap-12 lg:grid-cols-[1fr_0.85fr]"><div data-reveal><span className="mb-4 inline-block rounded-full border border-white/10 px-4 py-1.5 text-xs font-semibold text-white/60 md:mb-6">Próximo passo</span><h2 className="mb-4 max-w-3xl text-2xl font-bold leading-tight text-white sm:text-3xl md:mb-6 md:text-5xl">Entenda o melhor caminho antes de abrir, migrar ou reorganizar seu CNPJ.</h2><p className="mb-7 max-w-2xl text-sm leading-6 text-white/70 md:mb-10 md:text-lg md:leading-relaxed">O diagnóstico inicial organiza o contexto antes de discutir enquadramento, documentos, prazo e proposta.</p><div className="grid grid-cols-2 gap-3 sm:flex sm:flex-wrap sm:gap-4"><a href="#lead-form" onClick={() => trackConversionEvent("cta_clicked", { source: "final_primary", destination: "lead_form" })} className="inline-flex min-h-12 items-center justify-center gap-2 whitespace-nowrap rounded-full bg-brand-red px-3 py-3 text-center text-xs font-semibold leading-tight text-white shadow-[0_4px_20px_-4px_rgba(215,25,32,0.5)] transition-transform hover:-translate-y-0.5 sm:px-8 sm:py-3.5 sm:text-sm">Fazer diagnóstico <ArrowRight className="h-4 w-4" strokeWidth={1.75} /></a><WhatsAppLink source="final_whatsapp" intent="Quero falar com a Vidotti e entender os próximos passos para meu CNPJ." className="inline-flex min-h-12 items-center justify-center gap-2 whitespace-nowrap rounded-full border border-white/20 px-3 py-3 text-center text-xs font-semibold leading-tight text-white transition-colors hover:bg-white/5 sm:px-8 sm:py-3.5 sm:text-sm">Fale no WhatsApp</WhatsAppLink></div></div><div className="border-y border-white/10 py-5 md:py-8" data-reveal="mask" data-reveal-delay="200"><h3 className="text-xl font-bold text-white md:text-2xl">No diagnóstico inicial</h3><ul className="mt-4 space-y-3 md:mt-6 md:space-y-4">{closingPoints.map((point) => (<li key={point} className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-brand-red" strokeWidth={1.75} /><span className="text-sm leading-6 text-white/70 md:leading-relaxed">{point}</span></li>))}</ul><div className="mt-5 border-t border-white/10 pt-5 md:mt-8"><p className="text-sm font-semibold text-white">Canal principal</p><p className="mt-2 text-sm leading-6 text-white/60 md:leading-relaxed">WhatsApp da Vidotti com atendimento humano.</p></div></div></div></div></section>
  );
}
